import { describe, expect, it } from "vitest";

import { Argon2PasswordHasher } from "@/src/infrastructure/auth/argon2-password-hasher";

const PYTHON_PWDLIB_HASH =
  "$argon2id$v=19$m=65536,t=3,p=4$KlCnKZTx7Q1W6d/ueALEYg$11aPxD+pIG85UUHdRqYb5hmx/ok2F55t8RxARCPoi6c";

describe("Argon2PasswordHasher", () => {
  const hasher = new Argon2PasswordHasher();

  it("verifies a hash generated by the existing Python pwdlib adapter", async () => {
    await expect(
      hasher.verify("CompatibilityPassword123!", PYTHON_PWDLIB_HASH),
    ).resolves.toBe(true);
    await expect(hasher.verify("wrong", PYTHON_PWDLIB_HASH)).resolves.toBe(
      false,
    );
  });

  it("creates hashes with the production-compatible Argon2id profile", async () => {
    const hash = await hasher.hash("CompatibilityPassword123!");

    const [, algorithm, version, encodedParameters, salt, digest] =
      hash.split("$");
    const parameters = Object.fromEntries(
      (encodedParameters ?? "").split(",").map((parameter) => {
        const [name, value] = parameter.split("=");
        return [name, Number(value)];
      }),
    );

    expect(algorithm).toBe("argon2id");
    expect(version).toBe("v=19");
    expect(parameters).toEqual({ m: 65_536, p: 4, t: 3 });
    expect(Buffer.from(salt!, "base64")).toHaveLength(16);
    expect(Buffer.from(digest!, "base64")).toHaveLength(32);
    await expect(
      hasher.verify("CompatibilityPassword123!", hash),
    ).resolves.toBe(true);
  });
});
